import { useEffect, useRef, useId } from "react";
import Head from "next/head";
import Image from "next/image";
import GLogo from "../components/icons/GLogo";
import HeroImage from "../public/hero.svg";
import Cascade from "../components/Cascade";
import TechOrbit from "../components/TechOrbit/TeckOrbit";
import Hr from "../components/Hr";
import Projects from "../components/Projects/Projects";
import { Nav, NavList, Item } from "../components/Nav/Nav";

export default function Home() {
  
  const section1Ref = useRef(null);
  const section2Ref = useRef(null);
  const section3Ref = useRef(null);

const key = Math.random() * 10

  const scrollTo = (node) => {
    const position = node.getBoundingClientRect().top + window.scrollY;
    window.scrollTo({ top: position, behavior: "smooth" });
  };

  const handleNavItemClick = (e, section) => {
    e.preventDefault();
    scrollTo(section);
  };

  return (
    <>
      <Head>
        <title>Gailani.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>
          <div className="relative flex justify-between items-center container mx-auto mb-8 py-12">
            <GLogo />
            <Nav>
              <NavList>
                <a
                  to={section1Ref.current}
                  onClick={(e) => {
                    handleNavItemClick(e, section1Ref.current);
                  }}
                >
                  Tech I build with
                </a>
                <a
                  to={section2Ref.current}
                  onClick={(e) => {
                    handleNavItemClick(e, section2Ref.current);
                  }}
                >
                  Things I built
                </a>
                <a
                  to={section3Ref.current}
                  onClick={(e) => {
                    handleNavItemClick(e, section3Ref.current);
                  }}
                >
                  Get in touch
                </a>
              </NavList>
            </Nav>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 items-center container mx-auto">
            <Cascade className="mb-8" before="#">
              <h1 className="text-8xl sm:text-9xl lg:text-9xl xl:text-12xl 2xl:text-15xl font-display transition-all">
                Hello <br />
                world!
              </h1>
            </Cascade>
            <div>
              <Image
                aria-hidden="true"
                src={HeroImage}
                alt="building an app in a code editor"
              />
            </div>
          </div>
          <Hr className="mb-12" />
          <div className="container mx-auto mb-12">
            <p className="flex items-center">
              <span className="text-6xl mr-8">👋</span>
              <span className="text-2xl sm:text-4xl font-bold text-palette-blue-900 dark:text-palette-grey">
                Hi, I&apos;m Yaseen, <br />I build quality things for the web!
              </span>
            </p>
          </div>
        </header>
        <Hr className="sm:mb-12 md:mb-20" />
        <main>
          <section
            ref={section1Ref}
            className="pt-8 container mx-auto mb-8 sm:mb-12 md:mb-20"
          >
            <Cascade before="##">
              <h2 className="text-3xl sm:text-5xl lg:text-6xl text-palette-blue-900 font-display mb-8">
                Tech I build with
              </h2>
            </Cascade>
            <div className="grid grid-cols-12">
              <TechOrbit />
            </div>
          </section>
          <Hr className="sm:mb-12 md:mb-20" />
          <section ref={section2Ref} className="pt-8 container mx-auto">
            <Cascade before="##">
              <h2 className="text-3xl sm:text-5xl lg:text-6xl text-palette-blue-900  font-display mb-8">
                Things I built
              </h2>
            </Cascade>
            <div>
              <Projects />
            </div>
          </section>
          <Hr className="sm:mb-12 md:mb-20" />
          <section ref={section3Ref} className="pt-8 container mx-auto mb-8">
            <Cascade before="##">
              <h2 className="text-3xl sm:text-5xl lg:text-6xl text-palette-blue-900  font-display mb-8">
                Get in touch
              </h2>
            </Cascade>
            <input
              disabled
              type="text"
              className="border p-4 rounded-xl sm:w-96"
              placeholder="Enter you email"
            />
          </section>
        </main>
        <Hr />
        <footer className="container mx-auto py-8 flex justify-between">
          <GLogo small />
          <span className="text-neutral-700 dark:text-neutral-400">
            © Gailani {new Date().getFullYear()}
          </span>
        </footer>
      </div>
    </>
  );
}
